---
- name: Ensure required dependencies are present.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Elasticsearch apt key.
  get_url:
    url: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
    dest: '/etc/apt/trusted.gpg.d/elasticsearch.gpg'

- name: Add Filebeat repository.
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/elasticsearch.gpg] https://artifacts.elastic.co/packages/{{ filebeat_version }}/apt stable main'
    state: present
    update_cache: true
