grafana_security:
  admin_user: admin
  admin_password: password

grafana_datasources:
 - name: "Prometheus"
   type: "prometheus"
   url: "http://{{ groups['monitoring-stack'][0] }}:9090"

grafana_dashboards:
 - dashboard_id: '11074'
   revision_id: '9'
   datasource: 'Prometheus'

prometheus_targets:
  node:
    - targets:
        - localhost:9100
