grafana_security:
  admin_user: admin
  admin_password: password

grafana_datasources:
 - name: "Prometheus"
   type: "prometheus"
   url: "http://{{ groups['monitoring-stack'][0] }}:9090"

grafana_dashboards:
  - dashboard_id: '11074'
    revision_id: '9'
    datasource: 'Prometheus'
  - dashboard_id: '1860'
    revision_id: '37'
    datasource: 'Prometheus'
  - dashboard_id: '4202'
    revision_id: '1'
    datasource: 'Prometheus'

prometheus_targets:
  node:
    - targets:
        - localhost:9100

prometheus_alertmanager_config:
  - static_configs:
      - targets: ["{{ groups['monitoring-stack'][0] }}:9093"]

alertmanager_slack_api_url: 'https://hooks.slack.com/services/xxx/xxx/xxx'
alertmanager_smtp:
  from: 'alerts@example.com'
  smarthost: 'smtp.example.com:587'
  auth_username: 'smtp_username'
  auth_password: 'smtp_password'

alertmanager_receivers:
  - name: slack
    slack_configs:
      - send_resolved: true
        channel: '#alerts'
  - name: 'email'
    email_configs:
      - to: 'alerts@example.com'

alertmanager_route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: '1h'
  receiver: 'slack'
  routes:
    - match:
        severity: critical
      receiver: 'email'