---
- name: Install or Upgrade kube-logging-stack fluent-bit
  kubernetes.core.helm:
    name: "{{ kube_logging_stack_fluent_bit_release_name }}"
    namespace: "{{ kube_logging_stack_fluent_bit_namespace }}"
    chart_ref: "{{ kube_logging_stack_fluent_bit_chart_ref }}"
    create_namespace: true
    wait: true
    timeout: 600s
    values: "{{ kube_logging_stack_fluent_bit_values }}"
  register: _kube_logging_stack_fluent_bit_info

- name: Print information about kube-logging-stack kibana deployment
  debug:
    msg: "{{ _kube_logging_stack_fluent_bit_info.status }}"
