---
users:
  "{{ user_name }}":
    state: present
    sudo: true
    password: "{{ remote_user_password | password_hash('sha512') }}" # 

    # ssh_public_key: "Add your ssh public key here"
    ssh_public_key: "{{ ssh_key }}"
    sudo_no_password: true
