nginx_extra_http_options: |
  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

nginx_upstreams:
  - name: grafana
    servers:
      - "{{ groups['monitoring-stack'][0] }}:3000"
  - name: kibana
    servers:
      - "{{ groups['logging-stack'][0] }}:5601"

nginx_vhosts:
  - server_name: "grafana.localhost"
    listen: "80"
    root: "/usr/share/nginx/html"
    index: "index.html index.htm"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "grafana.localhost.conf"
    extra_parameters: |
      location / {
        proxy_set_header Host $host;
        proxy_pass http://grafana;
      }

      location /grafana/api/live/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_pass http://grafana;
      }
  - server_name: "kibana.localhost"
    listen: "80"
    root: "/usr/share/nginx/html"
    index: "index.html index.htm"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "kibana.localhost.conf"
    extra_parameters: |
      location / {
        proxy_set_header Host $host;
        proxy_pass http://kibana;
      }
