---
- name: Deploy Monitoring Stack on Kubernetes
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../variables/kubernetes/env/common.yml
  roles:
    - role: kube-prometheus-stack
      tags: kube-prometheus-stack
  tags: kube-monitoring-stack

- name: Deploy Logging Stack on Kubernetes
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../variables/kubernetes/env/common.yml
  roles:
    - role: kube-elasticsearch
      tags: kube-elasticsearch
    - role: kube-kibana
      tags: kube-kibana
    - role: kube-fluent-bit
      tags: kube-fluent-bit
  tags: kube-logging-stack
