---
- name: Deploy Monitoring Stack
  hosts: monitoring-stack
  become: true
  vars_files:
    - ../variables/ansible/env/common.yml
  roles:
    - role: prometheus
      tags: monitoring-stack, prometheus
    - role: alertmanager
      tags: monitoring-stack, alertmanager
    - role: blackbox_exporter
      tags: monitoring-stack, blackbox_exporter
    - role: grafana
      tags: monitoring-stack, grafana

- name: Deploy Exporters
  hosts: all
  ignore_unreachable: true
  become: true
  vars_files:
    - ../variables/ansible/env/common.yml
  roles:
    - role: node_exporter
      tags: exporter, monitoring-stack, node_exporter
    - role: process_exporter
      tags: exporter, monitoring-stack, process_exporter

- name: Deploy Logging Stack
  hosts: logging-stack
  become: true
  vars_files:
    - ../variables/ansible/env/common.yml
  roles:
    - role: java
      tags: logging-stack, elasticsearch, java
    - role: elasticsearch
      tags: logging-stack, elasticsearch
    - role: elasticsearch-curator
      tags: logging-stack, elasticsearch-curator
    - role: logstash
      tags: logging-stack, logstash
    - role: kibana
      tags: logging-stack, kibana

- name: Deploy Log Collection
  hosts: all
  ignore_unreachable: true
  become: true
  vars_files:
    - ../variables/ansible/env/common.yml
  roles:
    - role: filebeat
      tags: logging-stack, log-collection

- name: Deploy Web Server
  hosts: nginx
  become: true
  vars_files:
    - ../variables/ansible/env/common.yml
    - ../variables/ansible/env/nginx.yml
  roles:
    - role: nginx
      tags: webserver, reverse-proxy, nginx
