---
- name: Install or Upgrade kube-prometheus-stack
  kubernetes.core.helm:
    name: "{{ kube_prometheus_stack_release_name }}"
    namespace: "{{ kube_prometheus_stack_namespace }}"
    chart_ref: "{{ kube_prometheus_stack_chart_ref }}"
    create_namespace: true
    wait: true
    timeout: 600s
    values: "{{ kube_prometheus_stack_values }}"
  register: _kube_prometheus_stack_info

- name: Print information about kube-prometheus-stack deployment
  debug:
    msg: "{{ _kube_prometheus_stack_info.status }}"
